#!/bin/sh

elephantdrive_path=/usr/pbi/elephantdrive-$(uname -m)
tmpfile=$(mktemp /tmp/.XXXXXX)

grep -v 'elephantdrive_' /etc/rc.conf > ${tmpfile}
cat ${elephantdrive_path}/etc/rc.conf >> ${tmpfile}
mv ${tmpfile} /etc/rc.conf
